import { CheckCircle2, Database, FileCheck2, KeyRound, LockKeyhole, ShieldCheck, Trash2, UserCog } from "lucide-react";
import PageTitle from "../components/PageTitle";
export default function AdminGovernance(){return <>
<PageTitle eyebrow="DATA GOVERNANCE" title="Build privacy into every data pathway." subtitle="A governance workspace for consent, access, retention and audit controls. This frontend is DPDP Act-aligned in design; legal compliance requires verified production controls."/>
<div className="governance-status card"><div className="status-check"><ShieldCheck size={20}/></div><div><b>Privacy posture: design aligned</b><span>Production backend controls must enforce the policy—not the UI alone.</span></div><span className="status-chip success">Review ready</span></div>
<div className="governance-grid"><GovCard icon={<UserCog size={17}/>} title="Role-based access" status="Configured in UI" text="Student, counselor and admin workspaces expose different data surfaces." items={["Least-privilege roles","Separate counselor/admin routes","Human review for interventions"]}/><GovCard icon={<FileCheck2 size={17}/>} title="Consent & purpose" status="Backend required" text="Collect clear consent and use data only for stated wellbeing purposes." items={["Notice before collection","Purpose limitation","Withdraw / update mechanisms"]}/><GovCard icon={<Database size={17}/>} title="Data minimization" status="Design ready" text="Prefer aggregate analytics and minimum necessary records." items={["Aggregate reporting","Anonymized identifiers","No unnecessary profile fields"]}/><GovCard icon={<Trash2 size={17}/>} title="Retention & deletion" status="Backend required" text="Define retention schedules and secure deletion workflows." items={["Retention schedule","Deletion requests","Secure disposal"]}/></div>
<section className="card workspace-card"><div className="card-top"><div><span className="eyebrow">AUDIT TRAIL</span><h2>Governance activity</h2><p className="panel-subtext">Example events the backend should record for accountable administration.</p></div><span className="privacy-tag">Tamper-evident logging recommended</span></div><div className="audit-list"><Audit icon={<KeyRound size={14}/>} title="Admin role accessed aggregate analytics" time="Today · 10:42"/><Audit icon={<LockKeyhole size={14}/>} title="Counselor access policy reviewed" time="Yesterday · 16:20"/><Audit icon={<Database size={14}/>} title="Retention rule updated" time="Sep 2 · 11:05"/><Audit icon={<CheckCircle2 size={14}/>} title="Privacy notice version approved" time="Aug 30 · 14:18"/></div></section>
</>}
function GovCard({icon,title,status,text,items}){return <section className="card gov-card"><div className="gov-icon">{icon}</div><span className="status-chip success">{status}</span><h3>{title}</h3><p>{text}</p><div className="gov-items">{items.map(x=><span key={x}><CheckCircle2 size={12}/>{x}</span>)}</div></section>}
function Audit({icon,title,time}){return <div className="audit-row"><div className="audit-icon">{icon}</div><div><b>{title}</b><small>{time}</small></div><span className="audit-ok">Recorded</span></div>}
