import { Activity, BarChart3, Database, ShieldCheck, Target, TrendingUp, Users, Zap } from "lucide-react";
import PageTitle from "../components/PageTitle";
import StatCard from "../components/StatCard";
import PrivacyNote from "../components/PrivacyNote";
import { departments } from "../data";

export default function AdminDashboard() {
  return <>
    <PageTitle eyebrow="CAMPUS INTELLIGENCE" title="Institutional wellbeing overview." subtitle="Aggregated trends for planning capacity, prevention and campus-level support without exposing individual student records." action={<div className="mini-user"><div className="avatar">A</div><span>Campus Admin</span></div>} />
    <div className="signal-banner"><ShieldCheck size={20}/><div><b>CampusPulse Signal Intelligence <span className="privacy-tag">AGGREGATED & ANONYMIZED</span></b><span>Administrative analytics are designed around aggregate signals, access controls and purpose-limited reporting.</span></div></div>
    <div className="stats-grid admin-stats"><StatCard label="Total population" value="1,770" detail="6 active departments" icon={Users}/><StatCard label="Stable signal rate" value="77.4%" detail="+1.8% vs last month" progress={77} icon={ShieldCheck}/><StatCard label="Moderate support" value="16.6%" detail="Wellness Zone active" progress={17} icon={Activity}/><StatCard label="Priority review rate" value="5.2%" detail="Human care queue" progress={5} icon={Zap}/></div>
    <div className="admin-dashboard-grid"><section className="card heatmap-card"><div className="card-top"><div><span className="eyebrow">DEPARTMENT VIEW</span><h2>Campus department wellbeing heatmap</h2><p className="panel-subtext">Department-level distribution for proactive institutional allocation.</p></div><span className="privacy-tag">Aggregated & anonymized</span></div><div className="dept-heatmap">{departments.map(d => <div className={`dept-tile ${d.tone}`} key={d.name}><div className="dept-title"><b>{d.name}</b><span>{d.students} students</span></div><div className="dept-counts"><span>Stable: {d.stable}</span><span>Mod: {d.moderate}</span><span>Priority: {d.priority}</span></div><div className="dept-bar"><i style={{ width: `${(d.stable/d.students)*100}%` }}/><i style={{ width: `${(d.moderate/d.students)*100}%` }}/><i style={{ width: `${(d.priority/d.students)*100}%` }}/></div><div className="dept-foot"><span>Avg Stress {d.stress}/10</span><span className={d.change.startsWith("+") ? "positive" : "negative"}>Att: {d.change}</span></div></div>)}</div></section><section className="card admin-insight-card"><div className="mini-panel-head"><div><span className="eyebrow">EXECUTIVE SIGNALS</span><h3>What deserves attention?</h3></div><Target size={18}/></div><div className="signal-list"><Signal icon="01" title="Peak stress window" text="Academic weeks may need extra counselor capacity and low-friction check-in reminders."/><Signal icon="02" title="Department variation" text="Electronics and Computer Science show higher priority proportions in this demo dataset." warning/><Signal icon="03" title="Support access" text="Keep counselor availability and emergency resources visible from student screens."/></div><button className="btn btn-primary admin-action">View planning recommendations</button></section></div>
    <section className="card forecasting-card"><div className="card-top"><div><span className="eyebrow">PREDICTIVE OUTLOOK</span><h2>Wellbeing outlook & stress forecasting</h2><p className="panel-subtext">Projected support demand across upcoming academic milestones. Forecasts are estimates, not clinical predictions.</p></div><TrendingUp size={18}/></div><div className="forecast-wrap"><div className="forecast-chart"><div className="forecast-grid"/><div className="forecast-area"/><svg viewBox="0 0 700 190" preserveAspectRatio="none"><polyline points="0,125 90,118 180,113 270,96 360,52 450,66 540,92 630,118 700,125" fill="none" stroke="currentColor" strokeWidth="4"/></svg><div className="forecast-labels"><span>Wk 1</span><span>Wk 2</span><span>Wk 3</span><span>Wk 4</span><span>Wk 5</span><span>Wk 6</span><span>Wk 7</span><span>Wk 8</span></div></div><div className="forecast-side"><b>Projected peak</b><strong>68%</strong><p>Expected support demand around midterm activity in this demo forecast.</p></div></div></section>
    <div className="admin-bottom-grid"><section className="card admin-insight-card"><div className="mini-panel-head"><div><span className="eyebrow">DATA GOVERNANCE</span><h3>Privacy controls to connect</h3></div><Database size={18}/></div><div className="governance-points"><div><ShieldCheck size={14}/><span>Purpose limitation</span></div><div><Users size={14}/><span>Role-based access</span></div><div><Database size={14}/><span>Data minimization</span></div><div><BarChart3 size={14}/><span>Aggregate reporting</span></div></div></section><section className="card admin-insight-card"><div className="mini-panel-head"><div><span className="eyebrow">PLANNING ACTIONS</span><h3>Recommended next steps</h3></div><Activity size={18}/></div><div className="task-list"><div><span className="task-dot"/><div><b>Protect counselor capacity</b><small>Review upcoming high-load periods.</small></div></div><div><span className="task-dot"/><div><b>Improve support visibility</b><small>Keep verified contacts one tap away.</small></div></div><div><span className="task-dot"/><div><b>Audit data pathways</b><small>Document consent, retention and access controls.</small></div></div></div></section></div>
    <PrivacyNote>“DPDP Act aligned” describes the frontend's privacy-oriented design, not a legal compliance guarantee. Production compliance requires verified notices, consent flows, security controls, retention rules and organizational processes.</PrivacyNote>
  </>;
}
function Signal({ icon, title, text, warning }) { return <div><span className={`signal-icon ${warning ? "warning" : ""}`}>{icon}</span><div><b>{title}</b><small>{text}</small></div></div>; }
