import { ArrowUpRight, Building2, Download, Filter, TrendingDown, TrendingUp } from "lucide-react";
import PageTitle from "../components/PageTitle";
import { departments } from "../data";
export default function AdminDepartments(){return <>
<PageTitle eyebrow="DEPARTMENT TRENDS" title="Compare wellbeing patterns across campus." subtitle="Aggregate department trends support resource allocation, prevention planning and leadership reporting." action={<button className="btn btn-soft"><Download size={14}/> Export report</button>}/>
<div className="role-kpi-grid"><Kpi label="Departments" value="6" detail="Active reporting units"/><Kpi label="Highest avg stress" value="7.1/10" detail="Electronics & Comm" tone="warning"/><Kpi label="Largest population" value="420" detail="Computer Science & Eng"/><Kpi label="Priority share" value="5.2%" detail="Campus aggregate" tone="danger"/></div>
<section className="card workspace-card"><div className="workspace-toolbar"><div><span className="eyebrow">DEPARTMENT COMPARISON</span><h2>Current signals</h2></div><button className="btn btn-soft btn-small"><Filter size={13}/> All departments</button></div><div className="department-table"><div className="department-head"><span>DEPARTMENT</span><span>POPULATION</span><span>STABLE</span><span>MODERATE</span><span>PRIORITY</span><span>CHANGE</span></div>{departments.map(d=><div className="department-row" key={d.name}><div><Building2 size={15}/><b>{d.name}</b></div><span>{d.students}</span><span className="positive">{d.stable}</span><span className="warning-text">{d.moderate}</span><span className="danger-text">{d.priority}</span><span className={d.change.startsWith('+')?'positive':'negative'}>{d.change} {d.change.startsWith('+')?<TrendingUp size={11}/>:<TrendingDown size={11}/>}</span></div>)}</div></section>
<div className="two-col-workspace"><section className="card workspace-card"><span className="eyebrow">LEADERSHIP TAKEAWAYS</span><h3>Where capacity may matter most</h3><div className="takeaway"><b>1. Electronics & Communication</b><p>Highest average stress in this demo dataset. Consider additional low-friction support visibility around academic peaks.</p><ArrowUpRight size={14}/></div><div className="takeaway"><b>2. Computer Science & Engineering</b><p>Largest student population and a notable priority segment. Capacity planning can account for volume.</p><ArrowUpRight size={14}/></div><div className="takeaway"><b>3. Business Management</b><p>Lower aggregate stress and positive change suggest current support visibility is stable.</p><ArrowUpRight size={14}/></div></section><section className="card workspace-card"><span className="eyebrow">RESOURCE ALLOCATION</span><h3>Suggested focus</h3><div className="allocation"><Alloc label="Counselor hours" value="74%"/><Alloc label="Outreach capacity" value="62%"/><Alloc label="Workshop slots" value="48%"/><Alloc label="Peer support" value="56%"/></div></section></div>
</>}
function Kpi({label,value,detail,tone=''}){return <div className={`card role-kpi ${tone}`}><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>}
function Alloc({label,value}){return <div><span>{label}</span><b>{value}</b><i><em style={{width:value}}/></i></div>}
