import { CalendarDays, Info, ShieldCheck, TrendingUp, Zap } from "lucide-react";
import PageTitle from "../components/PageTitle";
export default function AdminForecast(){return <>
<PageTitle eyebrow="STRESS FORECASTING" title="Plan for upcoming support demand." subtitle="Forecasts are planning estimates around academic milestones, not clinical predictions or individual risk scores."/>
<div className="role-kpi-grid"><Kpi label="Projected peak" value="68%" detail="Week 5 · demo model" tone="warning"/><Kpi label="Baseline demand" value="43%" detail="Current planning level"/><Kpi label="Peak uplift" value="+25%" detail="Relative to baseline"/><Kpi label="Confidence" value="Moderate" detail="Use for planning only"/></div>
<section className="card forecast-large"><div className="card-top"><div><span className="eyebrow">8-WEEK OUTLOOK</span><h2>Wellbeing support demand</h2><p className="panel-subtext">Projected demand around midterms, assignment clusters and exam preparation.</p></div><span className="forecast-status"><TrendingUp size={13}/> Projected outlook</span></div><div className="large-forecast-chart"><div className="y-labels"><span>80</span><span>60</span><span>40</span><span>20</span></div><div className="chart-area"><div className="chart-fill"/><svg viewBox="0 0 800 250" preserveAspectRatio="none"><polyline points="0,165 100,154 200,148 300,128 400,55 500,80 600,118 700,154 800,165" fill="none" stroke="currentColor" strokeWidth="4"/></svg><div className="x-labels">{[1,2,3,4,5,6,7,8].map(x=><span key={x}>Wk {x}</span>)}</div></div></div></section>
<div className="forecast-events"><Event icon={<CalendarDays size={16}/>} week="Week 4" title="Assignment cluster" text="Prepare additional counselor appointment visibility."/><Event icon={<Zap size={16}/>} week="Week 5" title="Midterm window" text="Expected peak support demand in this demo forecast."/><Event icon={<ShieldCheck size={16}/>} week="Week 7" title="Recovery window" text="Monitor whether demand returns toward baseline."/></div>
<section className="card workspace-card"><div className="section-title-row"><div className="section-icon"><Info size={17}/></div><div><span className="eyebrow">ETHICS PRINCIPLE</span><h3>Forecasts inform resources, not labels</h3></div></div><p className="panel-subtext">Production forecasting should use validated aggregate data, documented assumptions, privacy controls and human oversight. Never use a forecast as a diagnosis or automated intervention decision.</p></section>
</>}
function Kpi({label,value,detail,tone=''}){return <div className={`card role-kpi ${tone}`}><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>}
function Event({icon,week,title,text}){return <div className="card forecast-event"><div className="section-icon">{icon}</div><span className="eyebrow">{week}</span><h3>{title}</h3><p>{text}</p></div>}
