import { Activity, ArrowUpRight, CalendarClock, CheckCircle2, Clock3, MessageCircle, ShieldCheck, TrendingDown, TrendingUp, Users, Zap } from "lucide-react";
import PageTitle from "../components/PageTitle";
import StatCard from "../components/StatCard";
import RiskBadge from "../components/RiskBadge";
import PrivacyNote from "../components/PrivacyNote";
import { priorityStudents } from "../data";

export default function CounselorDashboard() {
  return <>
    <PageTitle eyebrow="COUNSELOR CENTER" title="Student support command center." subtitle="Review prioritized signals, follow-ups and support requests while keeping intervention decisions human-led." action={<div className="mini-user"><div className="avatar">C</div><span>Counselor workspace</span></div>} />
    <div className="signal-banner"><ShieldCheck size={20}/><div><b>CampusPulse Signal Intelligence <span className="privacy-tag">PRIVACY PROTECTED</span></b><span>AI-generated support signals highlight longitudinal pattern changes. Final intervention decisions always belong to authorized human counselors.</span></div></div>
    <div className="stats-grid counselor-stats-wide"><StatCard label="Students monitored" value="420" detail="Across assigned caseload" icon={Users}/><StatCard label="Moderate support" value="8" detail="Wellness pathways active" icon={Activity}/><StatCard label="Priority review" value="3" detail="Human review queued" icon={Zap}/><StatCard label="Follow-ups due" value="6" detail="Next 7 days" icon={CalendarClock}/></div>
    <div className="counselor-dashboard-grid">
      <section className="card counselor-panel"><div className="card-top"><div><span className="eyebrow">STUDENT PRIORITY QUEUE</span><h2>Support signals needing attention</h2><p className="panel-subtext">Use the queue to decide where human review may be useful. Identifiers are anonymized in this frontend.</p></div><span className="queue-count">5 students</span></div><div className="priority-table"><div className="priority-head"><span>STUDENT</span><span>SUPPORT PRIORITY</span><span>TREND</span><span>RECOMMENDED ACTION</span></div>{priorityStudents.map(s => <div className="priority-row" key={s.id}><div><b>{s.id}</b><span>{s.department} · {s.year}</span></div><div><RiskBadge level={s.priority}/><small>Signal {s.score}</small></div><div className={`trend ${s.trend === "Improving" ? "improving" : "declining"}`}>{s.trend === "Improving" ? <TrendingUp size={11}/> : <TrendingDown size={11}/>} {s.trend}</div><div className="action-cell"><span>{s.note}</span><ArrowUpRight size={14}/></div></div>)}</div></section>
      <aside className="counselor-side-stack"><section className="card mini-panel"><div className="mini-panel-head"><div><span className="eyebrow">TODAY</span><h3>Follow-up plan</h3></div><CalendarClock size={18}/></div><div className="task-list"><div><span className="task-dot urgent"/><div><b>Priority review</b><small>3 cases awaiting human review</small></div></div><div><span className="task-dot"/><div><b>Check-in follow-up</b><small>4 students due today</small></div></div><div><span className="task-dot"/><div><b>Care-plan review</b><small>2 active plans this week</small></div></div></div></section><section className="card mini-panel"><div className="mini-panel-head"><div><span className="eyebrow">SUPPORT ACTIVITY</span><h3>Caseload pulse</h3></div><MessageCircle size={18}/></div><div className="activity-bars"><Bar label="Check-ins completed" value={82}/><Bar label="Follow-ups on time" value={91}/><Bar label="Wellness referrals" value={64}/></div></section></aside>
    </div>
    <section className="card counselor-panel messages-panel"><div className="card-top"><div><span className="eyebrow">STUDENT MESSAGES</span><h2>Requests from students</h2></div><span className="small-muted">Connect backend message API here</span></div><div className="message-grid"><MessageItem text="I'd like to talk about academic pressure." /><MessageItem text="Can I schedule a wellbeing appointment?" /><MessageItem text="I used the wellness activity and want to discuss how I'm feeling." /></div></section>
    <PrivacyNote>Use role-based access, consent, purpose limitation, minimum necessary data and human review when connecting the production backend. This UI does not make clinical decisions.</PrivacyNote>
  </>;
}
function Bar({ label, value }) { return <div><span>{label}</span><b>{value}%</b><i><em style={{ width: `${value}%` }}/></i></div>; }
function MessageItem({ text }) { return <div className="message-mini"><div className="avatar">S</div><div><b>Anonymous student</b><p>{text}</p><small>New · human response recommended</small></div><button className="btn btn-soft">Review</button></div>; }
