import { CalendarClock, CheckCircle2, FileText, HeartHandshake, Plus, ShieldCheck, UserRound } from "lucide-react";
import PageTitle from "../components/PageTitle";

const plans=[
 {id:"CP-2048", type:"Academic support", owner:"Counselor team", status:"Active", next:"Sep 8", note:"Weekly check-in + study planning"},
 {id:"CP-3127", type:"Wellbeing pathway", owner:"Rahul Verma", status:"Review due", next:"Sep 6", note:"Follow-up after check-in trend"},
 {id:"CP-5086", type:"Counselor follow-up", owner:"Dr. Meera Sharma", status:"Active", next:"Sep 10", note:"Review support access and stress context"}
];
export default function CounselorInterventions(){return <>
 <PageTitle eyebrow="INTERVENTIONS" title="Plan support actions with a human-first workflow." subtitle="Organize care-plan tasks, referrals and session follow-ups without turning automated signals into diagnoses." action={<button className="btn btn-primary"><Plus size={14}/> New support plan</button>}/>
 <div className="role-kpi-grid"><Kpi label="Active plans" value="7" detail="Across current caseload"/><Kpi label="Review due" value="2" detail="Within 72 hours" tone="warning"/><Kpi label="Referrals" value="4" detail="Awaiting confirmation"/><Kpi label="Completed" value="18" detail="This month" tone="success"/></div>
 <section className="card workspace-card"><div className="card-top"><div><span className="eyebrow">CARE PLAN WORKSPACE</span><h2>Current support plans</h2><p className="panel-subtext">Keep intervention notes concise and purpose-limited. Connect this table to your backend care-plan service later.</p></div><span className="privacy-tag">Human reviewed</span></div><div className="plan-list">{plans.map(p=><div className="plan-row" key={p.id}><div className="case-avatar"><HeartHandshake size={16}/></div><div className="case-main"><b>{p.id}</b><span>{p.type} · {p.owner}</span></div><span className={`status-chip ${p.status==='Review due'?'warning':'success'}`}>{p.status}</span><div className="plan-note"><b>{p.note}</b><small>Next review: {p.next}</small></div><button className="btn btn-soft btn-small">Open</button></div>)}</div></section>
 <div className="two-col-workspace"><section className="card workspace-card"><div className="section-title-row"><div className="section-icon"><CalendarClock size={17}/></div><div><span className="eyebrow">TODAY'S ACTIONS</span><h3>Intervention checklist</h3></div></div><div className="timeline"><Timeline title="Review CP-3127" meta="10:30 AM · follow-up" done/><Timeline title="Confirm referral pathway" meta="1:00 PM · external support"/><Timeline title="Update CP-5086 plan" meta="4:00 PM · care plan"/></div></section><section className="card workspace-card"><div className="section-title-row"><div className="section-icon"><FileText size={17}/></div><div><span className="eyebrow">SESSION NOTES</span><h3>Structured notes</h3></div></div><div className="note-template"><span><UserRound size={14}/> Student context</span><span><HeartHandshake size={14}/> Support action</span><span><CheckCircle2 size={14}/> Outcome</span><span><ShieldCheck size={14}/> Next step</span></div><p className="small-muted">Use your institutional note format when connecting the backend.</p></section></div>
 </>}
function Kpi({label,value,detail,tone=''}){return <div className={`card role-kpi ${tone}`}><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>}
function Timeline({title,meta,done}){return <div className="timeline-row"><div className={`timeline-dot ${done?'done':''}`}>{done?<CheckCircle2 size={12}/>:''}</div><div><b>{title}</b><small>{meta}</small></div><button className="btn btn-soft btn-small">{done?'View':'Open'}</button></div>}
