import { BarChart3, Download, ShieldCheck, TrendingDown, TrendingUp, Users } from "lucide-react";
import PageTitle from "../components/PageTitle";
import { departments } from "../data";
export default function CounselorAnalytics(){return <>
<PageTitle eyebrow="CAMPUS ANALYTICS" title="Institutional analytics for counselor capacity." subtitle="Use aggregate trends to understand support demand without exposing individual student records." action={<button className="btn btn-soft"><Download size={14}/> Export summary</button>}/>
<div className="role-kpi-grid"><Kpi label="Students monitored" value="1,770" detail="Across 6 departments"/><Kpi label="Stable signals" value="77.4%" detail="Aggregate campus rate" tone="success"/><Kpi label="Moderate support" value="16.6%" detail="Current pathways" tone="warning"/><Kpi label="Priority review" value="5.2%" detail="Human queue" tone="danger"/></div>
<section className="card workspace-card"><div className="card-top"><div><span className="eyebrow">DEPARTMENT SIGNALS</span><h2>Wellbeing distribution</h2><p className="panel-subtext">Aggregate view for staffing, outreach and prevention planning.</p></div><span className="privacy-tag">Anonymized</span></div><div className="analytics-dept-grid">{departments.map(d=><div className={`analytics-dept ${d.tone}`} key={d.name}><div className="analytics-dept-head"><b>{d.name}</b><span>{d.students}</span></div><div className="analytics-big"><strong>{d.stress}</strong><small>avg stress / 10</small></div><div className="dept-bar"><i style={{width:`${d.stable/d.students*100}%`}}/><i style={{width:`${d.moderate/d.students*100}%`}}/><i style={{width:`${d.priority/d.students*100}%`}}/></div><div className="analytics-foot"><span>Stable {d.stable}</span><span>Priority {d.priority}</span><b className={d.change.startsWith('+')?'positive':'negative'}>{d.change}</b></div></div>)}</div></section>
<div className="analytics-grid"><section className="card workspace-card"><div className="section-title-row"><div className="section-icon"><TrendingUp size={17}/></div><div><span className="eyebrow">SUPPORT DEMAND</span><h3>8-week counselor workload</h3></div></div><div className="bar-chart">{[42,48,51,58,67,74,61,55].map((v,i)=><div key={i}><i style={{height:`${v}%`}}/><span>W{i+1}</span></div>)}</div><div className="chart-legend"><span><i/>Historical</span><span><i/>Projected</span></div></section><section className="card workspace-card"><div className="section-title-row"><div className="section-icon"><Users size={17}/></div><div><span className="eyebrow">CAPACITY</span><h3>Coverage signals</h3></div></div><div className="capacity-row"><span>Assigned caseload</span><b>420</b></div><div className="capacity-row"><span>Open priority reviews</span><b>3</b></div><div className="capacity-row"><span>Follow-ups this week</span><b>9</b></div><div className="capacity-row"><span>Recommended coverage</span><b className="positive">Good</b></div></section></div>
<div className="analytics-callout"><ShieldCheck size={17}/><div><b>Privacy guardrail</b><p>Analytics should remain aggregate and purpose-limited. Avoid using this view to infer a diagnosis or label an individual student.</p></div></div>
</>}
function Kpi({label,value,detail,tone=''}){return <div className={`card role-kpi ${tone}`}><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>}
